### ISSUE TITLE
Bug.

### ISSUE THREAD

**Issue by D0n-A** [fire0shadow/vk-groups-album-downloader#2]
Доброго времени суток. Происходит следующее: при скачивании в каждом альбоме находятся лишь 50 первых фотографий.

**Comment by fire0shadow** [comment]
Здравствуйте. Добавил переменную 'photos_max_count', которая позволяет установить, сколько максимально можно выгрузить фотографий из альбома. Максимальное значение - 1000, больше к сожалению не позволяет API ВКонтакте. Хотя я не уверен, возможно ли в альбомах ВКонтакте вообще хранить больше 1000 фотографий.

**Comment by D0n-A** [comment]
Новый не буду открывать запрос - скажите, пожалуйста, а как же реализация скачивания "Фотографий со страницы сообщества"? Выходит - что данный альбом он пропускает...

**Comment by fire0shadow** [comment]
Почти полностью переработал скрипт - настройки передаются теперь через параметры командной строки, альбомы каждой группы сохраняются в отдельную папку, добавлена проверка существования отдельных файлов, а не всего альбома целиком. Добавил параметр --fetch-wall, с помощью которого можно добавить к альбомам и альбом "Фото со стены сообщества". При большом количестве фотографий на стене, выгрузка может занять некоторое время.
